// GENERATED FILE - DO NOT EDIT BY HAND.
// Sources: experiments/rootfs/system.seed + experiments/rootfs/plasma.seed.
// Profilo intenzionalmente parziale: storage, utenti, password e locale restano manuali.
{
  product: {
    id: "Slowroll",
  },

  software: {
    patterns: [],
    packages: [
      "7zip",
      "Mesa-dri",
      "Mesa-vulkan-device-select",
      "NetworkManager",
      "NetworkManager-bluetooth",
      "alsa-ucm-conf",
      "alsa-utils",
      "apparmor-parser",
      "apparmor-utils",
      "ark",
      "avahi",
      "bash-completion",
      "bluedevil6",
      "bluez",
      "bluez-obexd",
      "breeze6",
      "breeze6-cursors",
      "breeze6-decoration",
      "breeze6-style",
      "btrfsmaintenance",
      "btrfsprogs",
      "ca-certificates-mozilla",
      "cifs-utils",
      "criscore1",
      "criscore2",
      "cups",
      "cups-filters",
      "cups-pk-helper",
      "curl",
      "dbus-broker",
      "discover6",
      "discover6-backend-flatpak",
      "dolphin",
      "dosfstools",
      "dracut",
      "e2fsprogs",
      "efibootmgr",
      "exfatprogs",
      "firewalld",
      "flatpak",
      "fwupd",
      "fwupd-efi",
      "glibc-locale",
      "google-noto-coloremoji-fonts",
      "google-noto-sans-fonts",
      "gutenprint",
      "gwenview",
      "iproute2",
      "iputils",
      "kate",
      "kde-cli-tools6",
      "kde-gtk-config6",
      "kernel-default",
      "kernel-firmware-amdgpu",
      "kernel-firmware-mediatek",
      "kernel-firmware-realtek",
      "kglobalacceld6",
      "kio-admin",
      "kio-extras",
      "kio-fuse",
      "konsole",
      "kscreenlocker6",
      "kwalletmanager",
      "kwin6",
      "liberation-fonts",
      "libvulkan_radeon",
      "myrlyn",
      "nss-mdns",
      "ntfs-3g",
      "ntfsprogs",
      "nvme-cli",
      "okular",
      "openSUSE-release",
      "openSUSE-repos-Slowroll",
      "pam_kwallet6",
      "partitionmanager",
      "pciutils",
      "pipewire",
      "pipewire-alsa",
      "pipewire-pulseaudio",
      "plasma6-branding-openSUSE",
      "plasma6-disks",
      "plasma6-firewall",
      "plasma6-integration-plugin",
      "plasma6-nm",
      "plasma6-pa",
      "plasma6-print-manager",
      "plasma6-session",
      "plasma6-systemmonitor",
      "plasma6-theme-openSUSE",
      "plasma6-workspace",
      "plymouth",
      "plymouth-branding-openSUSE",
      "plymouth-dracut",
      "polkit",
      "polkit-kde-agent-6",
      "power-profiles-daemon",
      "powerdevil6",
      "rpm",
      "sdbootutil",
      "sdbootutil-kernel-install",
      "sdbootutil-snapper",
      "sddm-kcm6",
      "sddm-qt6",
      "sddm-qt6-branding-openSUSE",
      "shim",
      "skanlite",
      "smartmontools",
      "snapper",
      "snapper-zypp-plugin",
      "spectacle",
      "sudo",
      "systemd",
      "systemd-boot",
      "systemd-presets-branding-openSUSE",
      "systemsettings6",
      "timezone",
      "ucode-amd",
      "udisks2",
      "unar",
      "unzip",
      "upower",
      "usbutils",
      "wireplumber",
      "wpa_supplicant",
      "xdg-desktop-portal",
      "xdg-desktop-portal-kde6",
      "xdg-user-dirs",
      "xdg-utils",
      "xf86-input-libinput",
      "xorg-x11-server",
      "xwayland",
      "yast2",
      "yast2-apparmor",
      "yast2-bootloader",
      "yast2-control-center-qt",
      "yast2-packager",
      "yast2-scanner",
      "yast2-services-manager",
      "yast2-snapper",
      "yast2-storage-ng",
      "yast2-sysconfig",
      "zip",
      "zram-generator",
      "zstd",
      "zypper",
    ],
    extraRepositories: [
      {
        alias: "criscore",
        name: "mySlowrollOS criscore",
        url: "https://download.opensuse.org/repositories/home:/krism/openSUSE_Slowroll/",
        priority: 90,
      },
    ],
    onlyRequired: true,
  },

  scripts: {
    post: [
      {
        name: "myslowroll-system-policy",
        chroot: true,
        url: "./post-install.sh",
      },
    ],
  },
}
